"""diferencia os tipos de usuários

Revision ID: 93b115ee97ce
Revises: f1aea821cd65
Create Date: 2025-11-14 16:22:44.392657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b115ee97ce'
down_revision: Union[str, Sequence[str], None] = 'f1aea821cd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type_user', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type_user')
    # ### end Alembic commands ###
